---
language: ruby
rvm:
- 2.5.1
sudo: false
cache: bundler
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
env:
- TASK='jekyll:check'
- TASK='jekyll:check_external_links'
matrix:
  fast_finish: true
  allow_failures:
  - env: TASK='jekyll:check_external_links'
gemfile: gems.rb
script: bundle exec rake $TASK