title: "showcase"
description: "Simple portfolio-showcase Jekyll theme."
author:
  name: "showcase"

url: "https://vllur.github.io"
baseurl: /showcase
source: .
destination: ./_site
permalink: /:title
paginate: 2
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
exclude: [vendor]
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

owner: "vllur"
lang: "en_GB"
iso-lang: "en"

nav-first: "Lorem"
nav-first-link: "/"

nav-second: "Ipsum"
nav-second-link: "/"

footer: "Lorem ipsum dolor"
